### ISSUE TITLE
Error when running spatial_analysis_utils_v2_sh.py

### ISSUE THREAD

**Issue by Physical-Universe** [TopoXLab/MCSpatNet#1]
Hi, 

As  you can see below, I have been trying to recreate your project and all has gone well until I tried to run the 'spatial_analysis_utils_v2_sh.py' code. Their seems to be a mistake in the code relating to the 'iloc'. Could you please confirm what the issue may be?

Kind regards,
Monty

spatial_analysis_utils_v2_sh.py:364: RuntimeWarning: invalid value encountered in true_divide
  G_star = np.array([x if x>0 else 0 for x in len(fv_list)*np.array(Gs)/sum(Gs)])
Traceback (most recent call last):
  File "spatial_analysis_utils_v2_sh.py", line 500, in <module>
    r_used, K_pool, VK_pool, lamb_pool = pool([test_ppp, test_pp2, test_pp3], fun=Kest)
  File "spatial_analysis_utils_v2_sh.py", line 361, in pool
    Gs = [fv.iloc[k, 2] for fv in fv_list]
  File "spatial_analysis_utils_v2_sh.py", line 361, in <listcomp>
    Gs = [fv.iloc[k, 2] for fv in fv_list]
AttributeError: 'tuple' object has no attribute 'iloc'

**Comment by Physical-Universe** [comment]
Resolved - Thanks for you assistance!
